server:
  port: 9001

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME:admin}:${MONGO_PASSWORD:pass}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:user_mongo_db}?authSource=${MONGO_AUTH_SOURCE:admin}