apiVersion: v1
kind: Secret
metadata:
  name: simple-crud-mongo-uri-secret
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL215LXVzZXI6bXktcGFzc3dvcmRAbXktcmVsZWFzZS1tb25nb2RiOjI3MDE3L215LWRhdGFiYXNlP2F1dGhTb3VyY2U9bXktZGF0YWJhc2Umc3NsPWZhbHNlCg==
