apiVersion: v1
kind: Secret
metadata:
  name: simple-crud-mongo-uri-secret
type: Opaque
data:
  MONGO_URI: {{ printf "mongodb://%s:%s@%s:27017/my-database?authSource=my-database&ssl=false" .Values.mongodb.auth.username .Values.mongodb.auth.password (include "mongodb.fullname" .) | b64enc | quote }}
