{
 "title": "Crud-Simple dash",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Errors 4XX/5XX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (host, statuses) (label_replace(\nrate (nginx_ingress_controller_request_duration_seconds_count{path=~\"/otusapp.*\", exported_service=\"crud-simple-chart-service\", status=~\"[5,4].+\"}[1m])\n, \"statuses\", \"${1}XX\", \"status\", \"(.?).+\"))",
     "legendFormat": "{{statuses}}"
    }
   ]
  },
  { "title": "Panel Title", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le) (rate(crud_simple_http_server_requests_bucket{uri=~\"/user.*\"}[1m]))))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.95, (sum by (le) (rate(crud_simple_http_server_requests_bucket{uri=~\"/user.*\"}[1m]))))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, (sum by (le) (rate(crud_simple_http_server_requests_bucket{uri=~\"/user.*\"}[1m]))))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(1, (sum by (le) (rate(crud_simple_http_server_requests_bucket{uri=~\"/user.*\"}[1m]))))",
     "legendFormat": "100%"
    }
   ]
  },
  {
   "title": "CPU  usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{container=\"crud-simple-chart\"}*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": " RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri) (rate(crud_simple_http_server_requests_count{uri=~\"/user.*\"}[1m])) ",
     "legendFormat": "RPS {{uri}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{   container=\"crud-simple-chart\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Inserts to Users table",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_live_tup[1m])",
     "legendFormat": "User inserts"
    }
   ]
  },
  {
   "title": "DB  size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_database_size{datname='crudSimpleDb'}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Database blocks read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_blks_read[1m]))\n by (datname)\n"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } }
 ]
}